from screens.all_recipe_view import AllRecipeView
from screens.breakfast_view import BreakFastView
from screens.detail_screen import DetailScreen
from screens.dinner_view import DinnerView
from screens.home import HomePage
from screens.landing import LandingScreen
from screens.lunch_view import LunchView
from screens.recipe_screen import RecipeScreen
from screens.search import SearchScreen
from screens.window_manager import WindowManager